version: '3'
services:
  database:
    image: postgres
    container_name: birds-database
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /custom/mount:/var/lib/postgresql/data