version: '3'
services:
  fastapi_admin:
    build:
      context: admin
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
  postgresql_database:
    build:
      context: postgresql-database
      dockerfile: postgresql.Dockerfile
    env_file:
      - ./postgresql-database/postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - /custom/mount:/var/lib/postgresql/data