version: '3'
services:
  fastapi_admin:
    build:
      context: bird-service
      dockerfile: fastapi.Dockerfile
    env_file:
      - bird-service/fastapi.env
    volumes:
      - ./media:/tmp
    ports:
      - "8000:8000"

  postgresql_database:
    build:
      context: postgresql-database
      dockerfile: postgresql.Dockerfile
    env_file:
      - ./postgresql-database/postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi_admin
    ports:
      - "80:80"
volumes:
  pgdata: